name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate archive
        run: |
          git archive --format=tar.gz --prefix=pkgdrop-$GITHUB_REF_NAME/ -o pkgdrop-$GITHUB_REF_NAME.tar.gz HEAD

      - name: Upload release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          files: pkgdrop-$GITHUB_REF_NAME.tar.gz
          generate_release_notes: true
